apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: my-deployment
  name: my-deployment
  namespace: skg
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 32202
  selector:
    app: my-deployment
  type: NodePort
status:
  loadBalancer: {}
